[tool.poetry]
name = "research"
version = "0.1.0"
description = ""
authors = ["kojikojiprg <kojikoji.prg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.4"
pandas = "^1.0.4"
matplotlib = "^3.2.1"
opencv-python = "^4.2.0"
opencv-contrib-python = "^4.2.0"
scipy = "^1.5.0"
scikit-learn = "^0.23.2"
PyClustering = "^0.10.0"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
flake8 = "^3.8.2"
autopep8 = "^1.5.2"
youtube-dl = "^2020.6.6"
rope = "^0.17.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
