n_classes: 2
size: 4
n_linears: 2
hidden_dims:
- 16
- 8
n_rnns: 2
rnn_hidden_dim: 64
rnn_dropout: 0.0
pos_weight: 4
lr: 0.001
weight_decay: 1e-5
scheduler_rate: 0.99
pretrained_path: models/passing/pass_model_lstm_ep20.pth
