individual:
  indicator:
    position:
      default:
        th_ankle: 0.5  # threshold of ankle confidence score
        ratio: 1.2
        que_size: 30
        th_std: 1  # threshold of outlier
    face:
      default:
        ratio: 2.7  # eres position / difference between shoulder and hip
        que_size: 20
        th_std: 1
    body:
      default:
        ratio: 2.2  # shoulder position / difference between shoulder and hip
        que_size: 20
        th_std: 1
    arm:
      default:
        que_size: 5
        th_std: 1
  keypoint:
    default:
      que_size: 10
      th_std: 1
      window: 3  # the moving average length for filling nan
      th_conf: 0.0  # threshold of confidence score

group:
  indicator:
    passing:
      default:
        gauss_mu: 200  # 距離に対するガウス分布の平均
        gauss_sig: 100  # 距離に対するガウス分布の分散
        wrist_gauss_mu: 100  # 手首の距離に対するガウス分布の平均
        wrist_gauss_sig: 80  # 手首の距離に対するガウス分布の分散
      cfg_path: "config/passing/pass_model_lstm.yaml"
    attention:
      default:
        angle: 10  # 視野角
        division: 20  # 計算するピクセル幅
        length: 150  # 視野の長さ
        sigma: 50  # 視野の長さを超えた範囲の分散
        seq_len: 30
        angle_th: 10
        count_th: 2

optim:
  epoch: 50
  lr: 0.001
  lr_rate: 1.0
  pos_weight: [1, 8]

dataset:
  batch_size: 4096
  train_ratio: 0.75
  val_ratio: 0.05
  random_seed: 128
  setting:
    "02":
      "001":
      # num     p1   p2   s1   e1
        # "01": [[  9,   3, 118, 139]]
        "01": []
        "02": [[ 11,  10, 136, 155], [ 13,  10, 253, 392]]
        "03": [[ 31,  27, 115, 127], [ 31,  27, 352, 364]]
        "04": [[ 42,  43, 135, 160]]
        "05": [[ 47,  51,  94, 111]]
        "06": [[ 58,  61,  51,  67], [ 58,  61, 178, 207]]
        # "07": [[ 76,  79,  88, 111]]
        "07": []
        "08": [[ 81,  85, 168, 184]]
        "09": [[ 97, 104, 172, 193]]
        "10": [[125, 119, 203, 232]]
        "11": [[134, 140, 236, 259]]
        "12": []
        "13": [[167, 166, 239, 262]]
        "14": []
        "15": [[191, 202, 490, 520]]
        "16": []
        "17": []
        "18": [[247, 251, 195, 228], [247, 251, 395, 445]]
        "19": [[259, 262, 170, 216]]
        "20": [[268, 270,  95, 116], [268, 266, 237, 259]]
        "21": [[288, 287, 113, 132]]
        "22": [[289, 295,  97, 115]]
        "23": [[309, 304, 124, 159]]

    "08":
      "001":
      # num     p1   p2   s1   e1
        "01": [[  6,   3, 102, 128]]
        # "02": [[ 21,  14, 117, 136]]
        "02": []
        "03": [[ 32,  26, 199, 221]]
        "04": [[ 41,  39,  87, 128]]
        "05": [[ 50,  52, 198, 248]]
        "06": [[ 57,  62,  75, 100]]
        "07": [[ 68,  70,  53,  64]]
        "08": [[ 74,  75, 370, 403]]
        "09": [[ 89,  91, 198, 214]]
        "10": [[ 99, 101, 204, 221]]
        "11": [[116, 115, 308, 326]]
        "12": [[136, 138, 183, 206]]
        "13": [[146, 147, 130, 150]]
        "14": [[156, 159, 155, 173]]
        "15": [[168, 169,  70,  88]]
        "16": [[178, 181, 136, 150]]
        "17": [[188, 189,  80,  94]]
        "18": [[195, 197,  81, 104]]
        "19": [[203, 206, 174, 296]]
        "20": [[215, 220,  81,  98]]
        "21": [[226, 228,  77,  88]]
        "22": []
        "23": [[242, 247,  60,  84]]
        "24": [[250, 252, 166, 206]]
        "25": [[271, 266, 189, 209]]
        "26": [[283, 278, 108, 118]]
        "27": [[297, 290, 142, 151]]
        "28": []
        "29": [[315, 316, 223, 245]]
        "30": [[321, 322, 140, 165]]
        "31": [[339, 332, 277, 289]]
        "32": [[342, 343, 200, 206], [342, 343, 329, 342]]
        "33": [[352, 353, 206, 246]]
        "34": [[361, 362, 113, 139]]
        "35": [[368, 370, 279, 300]]
        "36": [[380, 381, 140, 175]]
        "37": [[388, 389, 280, 730]]
        "38": [[395, 396, 110, 148]]
        "39": [[404, 410,  93, 153]]
        "40": [[412, 417,  64, 122]]
        "41": [[421, 422, 114, 128]]

    "09":
      "001":
      # num     p1   p2   s1   e1
        "01": [[  8,   1,  58, 113]]
        "02": [[ 29,  18,  83, 121]]
        "03": [[ 45,  40, 382, 535]]
        "04": [[ 60,  59, 327, 356]]
        "05": [[ 78,  75, 151, 171]]
        "06": [[ 82,  85, 187, 200]]
        "07": [[ 92,  96, 107, 132]]
        "08": [[102, 105, 255, 277]]
        "09": [[114, 116, 112, 132]]
