individual:
  indicator:
    position:
      default:
        th_ankle: 0.5  # threshold of ankle confidence score
        ratio: 1.2
        que_size: 30
        th_std: 1  # threshold of outlier
    face:
      default:
        ratio: 2.7  # eres position / difference between shoulder and hip
        que_size: 20
        th_std: 1
    body:
      default:
        ratio: 2.2  # shoulder position / difference between shoulder and hip
        que_size: 20
        th_std: 1
    arm:
      default:
        que_size: 5
        th_std: 1
  keypoint:
    default:
      que_size: 10
      th_std: 1
      window: 3  # the moving average length for filling nan
      th_conf: 0.0  # threshold of confidence score

group:
  indicator:
    passing:
      default:
        gauss_mu: 200  # 距離に対するガウス分布の平均
        gauss_sig: 100  # 距離に対するガウス分布の分散
        wrist_gauss_mu: 100  # 手首の距離に対するガウス分布の平均
        wrist_gauss_sig: 80  # 手首の距離に対するガウス分布の分散
      cfg_path: "config/passing/pass_model_lstm.yaml"
    attention:
      default:
        angle: 10  # 視野角
        division: 20  # 計算するピクセル幅
        length: 150  # 視野の長さ
        sigma: 50  # 視野の長さを超えた範囲の分散
        seq_len: 30
        angle_th: 10
        count_th: 2

optim:
  epoch: 50
  lr: 0.001
  lr_rate: 1.0
  pos_weight: [1, 10]

dataset:
  batch_size: 4096
  train_ratio: 0.65
  val_ratio: 0.05
  random_seed: 128
  frame_number:
    "02":
      "20210903":
      # num     p1   p2   s1   e1
        "01": [[  9,   3, 118, 139]]
        "02": [[ 11,  10, 136, 155], [ 13,  10, 253, 392]]
        "03": [[ 31,  27, 115, 127], [ 31,  27, 352, 364]]
        "04": [[ 43,  44, 135, 160]]
        "05": [[ 48,  52,  94, 111]]
        "06": [[ 63,  66,  51,  67], [ 63,  66, 178, 207]]
        "07": [[ 76,  79,  88, 111]]
        "08": [[ 86,  90, 168, 184]]
        "09": [[102, 109, 172, 193]]
        "10": [[131, 125, 203, 232]]
        "11": [[142, 148, 236, 259]]
        "12": []
        "13": [[178, 177, 239, 262]]
        "14": []
        "15": [[205, 213, 490, 520]]
        "16": []
        "17": []
        "18": [[265, 269, 195, 228], [265, 269, 395, 445]]
        "19": [[277, 280, 170, 216]]
        "20": [[286, 288,  95, 116], [286, 284, 237, 259]]
        "21": [[308, 307, 113, 132]]
        "22": [[309, 315,  97, 115]]
        "23": [[329, 324, 124, 159]]

    "08":
      "20210915":
      # num     p1   p2   s1   e1
        "01": [[  6,   3, 102, 128]]
        # "02": [[ 21,  14, 117, 136]]
        "02": []
        "03": [[ 32,  26, 199, 221]]
        "04": [[ 40,  38,  87, 128]]
        "05": [[ 49,  48, 198, 248]]
        "06": [[ 56,  61,  75, 100]]
        "07": [[ 67,  69,  53,  64]]
        "08": [[ 73,  74, 370, 403]]
        "09": [[ 88,  90, 198, 214]]
        "10": [[ 98, 100, 204, 221]]
        "11": [[114, 112, 308, 326]]
        "12": [[134, 136, 183, 206]]
        "13": [[143, 144, 130, 150]]
        "14": [[153, 156, 155, 173]]
        "15": [[165, 166,  70,  88]]
        "16": [[175, 178, 136, 150]]
        "17": [[185, 186,  80,  94]]
        "18": [[193, 195,  81, 104]]
        "19": [[202, 205, 174, 296]]
        "20": [[215, 220,  81,  98]]
        "21": [[227, 229,  77,  88]]
        "22": []
        "23": [[244, 249,  60,  84]]
        "24": [[252, 254, 166, 206]]
        "25": [[275, 270, 189, 209]]
        "26": [[287, 282, 108, 118]]
        "27": [[300, 294, 142, 151]]
        "28": []
        "29": [[317, 318, 223, 245]]
        "30": [[324, 325, 140, 165]]
        "31": [[342, 336, 277, 289]]
        "32": [[345, 346, 200, 206], [345, 346, 329, 342]]
        "33": [[355, 356, 206, 246]]
        "34": [[364, 365, 113, 139]]
        "35": [[371, 373, 279, 300]]
        "36": [[383, 384, 140, 175]]
        "37": [[392, 393, 280, 730]]
        "38": [[402, 403, 110, 148]]
        "39": [[411, 417,  93, 153]]
        "40": [[419, 424,  64, 122]]
        "41": [[428, 429, 114, 128]]

    "09":
      "20210706":
      # num     p1   p2   s1   e1
        "01": [[  8,   1,  58, 113]]
        "02": [[ 31,  20,  83, 121]]
        "03": [[ 47,  42, 382, 535]]
        "04": [[ 63,  62, 327, 356]]
        "05": [[ 81,  84, 151, 171]]
        "06": [[ 86,  89, 187, 200]]
        "07": [[ 96, 100, 107, 132]]
        "08": [[106, 109, 255, 277]]
        "09": [[118, 120, 112, 132]]
