dropouts:
- 0.1
- 0
hidden_dims:
- 128
- 64
n_classes: 2
n_linears: 2
n_rnns: 1
pretrained_path: models/passing/pass_model_lstm_recall_ep50.pth
rnn_dropout: 0.1
rnn_hidden_dim: 128
size: 4
weight: 32
