individual:
  indicator:
    position:
      default:
        th_ankle: 0.5  # threshold of ankle confidence score
        ratio: 1.2
        que_size: 30
        th_std: 1  # threshold of outlier
    face:
      default:
        ratio: 2.7  # eres position / difference between shoulder and hip
        que_size: 20
        th_std: 1
    body:
      default:
        ratio: 2.2  # shoulder position / difference between shoulder and hip
        que_size: 20
        th_std: 1
    arm:
      default:
        que_size: 5
        th_std: 1
  keypoint:
    default:
      que_size: 10
      th_std: 1
      window: 3  # the moving average length for filling nan
      th_conf: 0.0  # threshold of confidence score

group:
  indicator:
    passing:
      default:
        gauss_mu: 200  # 距離に対するガウス分布の平均
        gauss_sig: 100  # 距離に対するガウス分布の分散
        wrist_gauss_mu: 100  # 手首の距離に対するガウス分布の平均
        wrist_gauss_sig: 80  # 手首の距離に対するガウス分布の分散
      cfg_path: "config/passing/pass_model_lstm.yaml"
    attention:
      default:
        angle: 10  # 視野角
        division: 20  # 計算するピクセル幅
        length: 150  # 視野の長さ
        sigma: 50  # 視野の長さを超えた範囲の分散
        seq_len: 30
        angle_th: 10
        count_th: 2

optim:
  epoch:
  lr: 0.001
  lr_rate: 1.0
  pos_weight: [1, 10]

dataset:
  batch_size: 4096
  train_ratio: 0.65
  val_ratio: 0.05
  random_seed: 128
  frame_number:
    "02":
      "20210903":
      # num     p1   p2   s1   e1
        "01": [[  1,   3, 118, 118]]
        "02": [[ 10,   9, 136, 136], [ 12,   9, 253, 392]]
        "03": [[ 24,  20, 115, 115], [ 24,  20, 352, 364]]
        "04": [[ 37,  40, 135, 135]]
        "05": [[ 43,  50,  94,  94]]
        "06": [[ 52,  55,  51,  51], [ 52,  55, 178, 207]]
        "07": [[ 62,  64,  88,  88]]
        "08": [[ 67,  75, 168, 168]]
        "09": [[ 81,  88, 172, 172]]
        "10": [[102,  94, 203, 203]]
        "11": [[112, 118, 236, 236]]
        "12": [[]]
        "13": [[140, 136, 239, 239]]
        "14": [[]]
        "15": [[166, 169, 490, 490]]
        "16": [[]]
        "17": [[]]
        "18": [[201, 205, 195, 195], [201, 205, 395, 445]]
        "19": [[211, 214, 170, 170]]
        "20": [[220, 219,  95,  95], [220, 218, 237, 259]]
        "21": [[228, 230, 113, 113]]
        "22": [[231, 235,  97,  97]]
        "23": [[251, 247, 124, 124]]

    "08":
      "20210915":
      # num     p1   p2   s1   e1
        "01": [[  7,   3, 102, 128]]
        "02": [[   ,    , 117, 136]]
        "03": [[   ,    , 199, 221]]
        "04": [[   ,    ,  87, 128]]
        "05": [[   ,    , 198, 248]]
        "06": [[   ,    ,  75, 100]]
        "07": [[   ,    ,  53,  64]]
        "08": [[   ,    , 370, 403]]
        "09": [[   ,    , 198, 214]]
        "10": [[   ,    , 204, 221]]
        "11": [[   ,    , 308, 326]]
        "12": [[   ,    , 183, 206]]
        "13": [[   ,    , 130, 150]]
        "14": [[   ,    , 155, 173]]
        "15": [[   ,    ,  70,  88]]
        "16": [[   ,    , 136, 150]]
        "17": [[   ,    ,  80,  94]]
        "18": [[   ,    ,  81, 104]]
        "19": [[   ,    , 174, 296]]
        "20": [[   ,    ,  81,  98]]
        "21": [[   ,    ,  77,  88]]
        "22": [[   ,    ,    ,    ]]
        "23": [[   ,    ,  60,  84]]
        "24": [[   ,    , 166, 206]]
        "25": [[   ,    , 189, 209]]
        "26": [[   ,    , 108, 118]]
        "27": [[   ,    , 142, 151]]
        "28": [[   ,    ,    ,    ]]
        "29": [[   ,    , 223, 245]]
        "30": [[   ,    , 140, 165]]
        "31": [[   ,    , 277, 289]]
        "32": [[   ,    , 200, 206], [   ,    , 329, 342]]
        "33": [[   ,    , 206, 246]]
        "34": [[   ,    , 113, 139]]
        "35": [[   ,    , 279, 300]]
        "36": [[   ,    , 140, 175]]
        "37": [[   ,    , 280, 730]]
        "38": [[   ,    , 110, 148]]
        "39": [[   ,    ,  93, 153]]
        "40": [[   ,    ,  64, 122]]
        "41": [[   ,    , 114, 128]]

    "09":
      "20210706 ":
      # num     p1   p2   s1   e1
        "01": [[  8,   1,  58, 113]]
        "02": [[ 39,  27,  83, 121]]
        "03": [[ 58,  73, 382, 535]]
        "04": [[ 87,  86, 327, 356]]
        "05": [[110, 105, 151, 171]]
        "06": [[117, 120, 187, 200]]
        "07": [[129, 133, 107, 132]]
        "08": [[139, 142, 255, 277]]
        "09": [[153, 155, 112, 132]]
