passing:
  default:
    dist_mu: 157 #314.00  # 距離に対するガウス分布の平均
    dist_sig: 80.74 #161.49  # 距離に対するガウス分布の分散
    wrist_mu: 133.86 #267.72  # 手首の距離に対するガウス分布の平均
    wrist_sig: 74.95 #149.90  # 手首の距離に対するガウス分布の分散
    seq_len: 30  # sequence length of LSTM input
  cfg_path: "config/passing/pass_model_lstm_f1_ep100.yaml"

attention:
  default:
    angle: 10  # 視野角
    division: 20  # 計算するピクセル幅
    length: 150  # 視野の長さ
    sigma: 50  # 視野の長さを超えた範囲の分散
    seq_len: 30
    angle_th: 10
    count_th: 2
