passing:
  default:
    dist_mu: 220.65 # 距離に対するガウス分布の平均
    dist_sig: 119.58 # 距離に対するガウス分布の分散
    wrist_mu: 302.11 # 手首の距離に対するガウス分布の平均
    wrist_sig: 213.0 # 手首の距離に対するガウス分布の分散
    seq_len: 30  # sequence length of LSTM input
  cfg_path: "config/passing/pass_model_lstm_f1_ep120.yaml"

attention:
  default:
    angle: 10  # 視野角
    division: 20  # 計算するピクセル幅
    length: 100  # 視野の長さ
    sigma: 50  # 視野の長さを超えた範囲の分散
    seq_len: 30
  object_path: "config/attention/object_point.yaml"
