indicator:
  position:
    default:
      th_ankle: 0.5  # threshold of ankle confidence score
      ratio: 1.2
      que_size: 30
      th_std: 1  # threshold of outlier
  face:
    default:
      ratio: 2.7  # eres position / difference between shoulder and hip
      que_size: 20
      th_std: 1
  body:
    default:
      ratio: 2.2  # shoulder position / difference between shoulder and hip
      que_size: 20
      th_std: 1
  arm:
    default:
      que_size: 5
      th_std: 1

keypoint:
  default:
    que_size: 10
    th_std: 1
    window: 3  # the moving average length for filling nan
    th_conf: 0.0  # threshold of confidence score
