keypoint:
  detector: "hrnet"
  cfg_path:
    higher_hrnet: "config/higher-hrnet/w32_512_adam_lr1e-3.yaml"
    hrnet: "config/hrnet/w32_384x288.yaml"
    unitrack: "config/unitrack/barlowtwins.yaml"
  th_delete: 0.2 # threshold of confidence score of keypoints
  th_diff: 10  # threshold of difference for finding same keypoints
  th_count: 5
  batch_size: 4
